feat: [wip] working on the frame of the window
rpfaeffle/DHBW-Programming-1-Final-Project pull request #4
Opened 2024-02-01 17:07 UTC by tim02-k

Start to working on the frame of the game window

2024-02-05 14:32 UTC, rpfaeffle requested changes
Good work. I made some comments about things that could be changed before merging.

2024-02-05 14:32 UTC, rpfaeffle commented on src/main.py
> +            print(f"Reached Level: {self.score.level}")
We should be good to remove this now.

2024-02-05 14:32 UTC, rpfaeffle commented on src/core/application.py
> +            screen_size = [520, 520]
This wouldn't be necessary, but we can keep it.

2024-02-05 14:32 UTC, rpfaeffle commented on src/main.py
> +        self.score = Score(1, 0)
Maybe we can add default values on initialisation

2024-02-05 14:32 UTC, rpfaeffle commented on src/components/score.py
> +        self.background = Block((0, 0, 0), 0, 0, 240, 100)
This is not used, so we can remove it

2024-02-06 11:33 UTC, tim02-k commented on src/components/score.py
> +        self.background = Block((0, 0, 0), 0, 0, 240, 100)
We need this part, i tested the program when it's removed and it doesn't worked

2024-02-06 11:37 UTC, tim02-k commented on src/core/application.py
> +            screen_size = [520, 520]
Ok, i  keep this at 520

2024-02-06 12:46 UTC, merged